### ISSUE TITLE
Cannot pass in names into elipses argument of to_long

### ISSUE THREAD

**Issue by mhermher** [strengejacke/sjmisc#64]
Because of the `data_cols <- eval(substitute(list(...)))` line of to_long, name objects cannot be passed into the ellipses of this function if the names are defined outside the lexical scope of the function. 

To replicate:

`testit <- function(){
    mydat <- data.frame(age = c(20, 30, 40),
                        sex = c("Female", "Male", "Male"),
                        score_t1 = c(30, 35, 32),
                        score_t2 = c(33, 34, 37),
                        score_t3 = c(36, 35, 38),
                        speed_t1 = c(2, 3, 1),
                        speed_t2 = c(3, 4, 5),
                        speed_t3 = c(1, 8, 6))
    #this one works:
    sjmisc::to_long(mydat, "time", c("score", "speed"),
            c("score_t1", "score_t2", "score_t3"),
            c("speed_t1", "speed_t2", "speed_t3")
    )
    testcols <- c("speed_t1", "speed_t2", "speed_t3")
    #this equivalent one does not:
    sjmisc::to_long(mydat, "time", c("score", "speed"),
            c("score_t1", "score_t2", "score_t3"),
            testcols)
}
testit()`

The first call to sjmisc::to_long works, but the equivalent second call does not and throws an error because it cannot eval the term `testcols` within the function scope. I am actually not sure why there is an eval(substitute()) wrapped around list(...) in this case, but I have not read through the entire function.

I can't get the markdown of the code to newline and indent properly. Sorry about that.

**Comment by strengejacke** [comment]
If you need variable column names in a vector as argument, get the column indices:

```
mydat <-
  data.frame(
    age = c(20, 30, 40),
    sex = c("Female", "Male", "Male"),
    score_t1 = c(30, 35, 32),
    score_t2 = c(33, 34, 37),
    score_t3 = c(36, 35, 38),
    speed_t1 = c(2, 3, 1),
    speed_t2 = c(3, 4, 5),
    speed_t3 = c(1, 8, 6)
  )

sjmisc::to_long(
  mydat,
  "time",
  c("score", "speed"),
  c("score_t1", "score_t2", "score_t3"),
  c("speed_t1", "speed_t2", "speed_t3")
)

testcols <- c("speed_t1", "speed_t2", "speed_t3")

sjmisc::to_long(
  mydat,
  "time",
  c("score", "speed"),
  c("score_t1", "score_t2", "score_t3"),
  which(colnames(mydat) %in% testcols)
)
```

**Comment by strengejacke** [comment]
Wait, this works for me as well:

```
testcols <- c("speed_t1", "speed_t2", "speed_t3")

sjmisc::to_long(
    mydat,
    "time",
    c("score", "speed"),
    c("score_t1", "score_t2", "score_t3"),
    testcols
)
```

It's just that the variable has to exist in the global environment, so calling it from inside a function may cause troubles?

**Comment by strengejacke** [comment]
Ok, should work now. Will commit tonight.

**Comment by mhermher** [comment]
Hi, thanks for the reply. 

Yes, I noticed that it works in the global environment, but not if it is defined within a function that is called from the global environment. 

I have seen the eval(substitute(list(...))) pattern elsewhere and honestly I still don't understand the purpose of it. I have always just written list(...), so there may be some difference. The problem is that the expression is evaluated within the scope of the to_long function, when it does not find the names of the variables within its own scope, it reaches into it's parent environment (where it is defined), which i believe is GlobalEnv, so it skips over the calling function. 

Another option that might work is to use substitute(list(...), parent.frame()), which I think will pull in the values from the calling function, but I am not sure.

Anyway, thanks for the update and commit.

Mher
